/* SPDX-License-Identifier: MIT
 *
 * Copyright 2016-2021 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_MME_CTRL_LO_ARCH_DMA_TEN_COUT_REGS_H_
#define ASIC_REG_MME_CTRL_LO_ARCH_DMA_TEN_COUT_REGS_H_

/*
 *****************************************
 *   MME_CTRL_LO_ARCH_DMA_TEN_COUT
 *   (Prototype: MME_TENSOR)
 *****************************************
 */

#define mmMME_CTRL_LO_ARCH_DMA_TEN_COUT_VALID_ELEMENTS_0 0x0

#define mmMME_CTRL_LO_ARCH_DMA_TEN_COUT_VALID_ELEMENTS_1 0x4

#define mmMME_CTRL_LO_ARCH_DMA_TEN_COUT_VALID_ELEMENTS_2 0x8

#define mmMME_CTRL_LO_ARCH_DMA_TEN_COUT_VALID_ELEMENTS_3 0xC

#define mmMME_CTRL_LO_ARCH_DMA_TEN_COUT_VALID_ELEMENTS_4 0x10

#define mmMME_CTRL_LO_ARCH_DMA_TEN_COUT_ROI_SIZE_0 0x14

#define mmMME_CTRL_LO_ARCH_DMA_TEN_COUT_ROI_SIZE_1 0x18

#define mmMME_CTRL_LO_ARCH_DMA_TEN_COUT_ROI_SIZE_2 0x1C

#define mmMME_CTRL_LO_ARCH_DMA_TEN_COUT_ROI_SIZE_3 0x20

#define mmMME_CTRL_LO_ARCH_DMA_TEN_COUT_SPATIAL_STRIDES_0 0x24

#define mmMME_CTRL_LO_ARCH_DMA_TEN_COUT_SPATIAL_STRIDES_1 0x28

#define mmMME_CTRL_LO_ARCH_DMA_TEN_COUT_SPATIAL_STRIDES_2 0x2C

#define mmMME_CTRL_LO_ARCH_DMA_TEN_COUT_SPATIAL_STRIDES_3 0x30

#define mmMME_CTRL_LO_ARCH_DMA_TEN_COUT_START_OFFSET_0 0x34

#define mmMME_CTRL_LO_ARCH_DMA_TEN_COUT_START_OFFSET_1 0x38

#define mmMME_CTRL_LO_ARCH_DMA_TEN_COUT_START_OFFSET_2 0x3C

#define mmMME_CTRL_LO_ARCH_DMA_TEN_COUT_START_OFFSET_3 0x40

#define mmMME_CTRL_LO_ARCH_DMA_TEN_COUT_LOOP_STRIDE_0 0x44

#define mmMME_CTRL_LO_ARCH_DMA_TEN_COUT_LOOP_STRIDE_1 0x48

#define mmMME_CTRL_LO_ARCH_DMA_TEN_COUT_LOOP_STRIDE_2 0x4C

#define mmMME_CTRL_LO_ARCH_DMA_TEN_COUT_LOOP_STRIDE_3 0x50

#define mmMME_CTRL_LO_ARCH_DMA_TEN_COUT_LOOP_STRIDE_4 0x54

#endif /* ASIC_REG_MME_CTRL_LO_ARCH_DMA_TEN_COUT_REGS_H_ */
