/* SPDX-License-Identifier: MIT
 *
 * Copyright 2016-2021 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_PDMA_CH_A_PQM_CH_MASKS_H_
#define ASIC_REG_PDMA_CH_A_PQM_CH_MASKS_H_

/*
 *****************************************
 *   PDMA_CH_A_PQM_CH
 *   (Prototype: PQM_CH_A)
 *****************************************
 */

/* PDMA_CH_A_PQM_CH_ADDR_HI */
#define PDMA_CH_A_PQM_CH_ADDR_HI_VAL_S 0
#define PDMA_CH_A_PQM_CH_ADDR_HI_VAL_M 0xFFFFFFFF

/* PDMA_CH_A_PQM_CH_ADDR_LO */
#define PDMA_CH_A_PQM_CH_ADDR_LO_VAL_S 0
#define PDMA_CH_A_PQM_CH_ADDR_LO_VAL_M 0xFFFFFFFF

/* PDMA_CH_A_PQM_CH_CTRL */
#define PDMA_CH_A_PQM_CH_CTRL_PTR_SIZE_S 0
#define PDMA_CH_A_PQM_CH_CTRL_PTR_SIZE_M 0xFFFF
#define PDMA_CH_A_PQM_CH_CTRL_INDEX_S 16
#define PDMA_CH_A_PQM_CH_CTRL_INDEX_M 0x3FF0000

/* PDMA_CH_A_PQM_CH_PI */
#define PDMA_CH_A_PQM_CH_PI_VAL_S 0
#define PDMA_CH_A_PQM_CH_PI_VAL_M 0xFFFFFFFF

/* PDMA_CH_A_PQM_CH_CI */
#define PDMA_CH_A_PQM_CH_CI_VAL_S 0
#define PDMA_CH_A_PQM_CH_CI_VAL_M 0xFFFFFFFF

/* PDMA_CH_A_PQM_CH_CP_PRED */
#define PDMA_CH_A_PQM_CH_CP_PRED_VAL_S 0
#define PDMA_CH_A_PQM_CH_CP_PRED_VAL_M 0xFFFFFFFF

/* PDMA_CH_A_PQM_CH_DESC_SUBMIT_FIFO_CFG */
#define PDMA_CH_A_PQM_CH_DESC_SUBMIT_FIFO_CFG_MODE_S 0
#define PDMA_CH_A_PQM_CH_DESC_SUBMIT_FIFO_CFG_MODE_M 0x3
#define PDMA_CH_A_PQM_CH_DESC_SUBMIT_FIFO_CFG_WRITE_MODE_S 2
#define PDMA_CH_A_PQM_CH_DESC_SUBMIT_FIFO_CFG_WRITE_MODE_M 0x4

/* PDMA_CH_A_PQM_CH_DESC_PTR_RLS_CFG */
#define PDMA_CH_A_PQM_CH_DESC_PTR_RLS_CFG_MSG_ENABLE_S 0
#define PDMA_CH_A_PQM_CH_DESC_PTR_RLS_CFG_MSG_ENABLE_M 0x1
#define PDMA_CH_A_PQM_CH_DESC_PTR_RLS_CFG_MSG_TYPE_S 1
#define PDMA_CH_A_PQM_CH_DESC_PTR_RLS_CFG_MSG_TYPE_M 0x2
#define PDMA_CH_A_PQM_CH_DESC_PTR_RLS_CFG_MAX_INFLIGHT_S 2
#define PDMA_CH_A_PQM_CH_DESC_PTR_RLS_CFG_MAX_INFLIGHT_M 0x3C

/* PDMA_CH_A_PQM_CH_DESC_PTR_RLS_MSG_ADDR_L */
#define PDMA_CH_A_PQM_CH_DESC_PTR_RLS_MSG_ADDR_L_VAL_S 0
#define PDMA_CH_A_PQM_CH_DESC_PTR_RLS_MSG_ADDR_L_VAL_M 0xFFFFFFFF

/* PDMA_CH_A_PQM_CH_DESC_PTR_RLS_MSG_ADDR_H */
#define PDMA_CH_A_PQM_CH_DESC_PTR_RLS_MSG_ADDR_H_VAL_S 0
#define PDMA_CH_A_PQM_CH_DESC_PTR_RLS_MSG_ADDR_H_VAL_M 0xFFFFFFFF

/* PDMA_CH_A_PQM_CH_DESC_PTR_RLS_MSG_FREQ */
#define PDMA_CH_A_PQM_CH_DESC_PTR_RLS_MSG_FREQ_VAL_S 0
#define PDMA_CH_A_PQM_CH_DESC_PTR_RLS_MSG_FREQ_VAL_M 0xFFFFFFFF

/* PDMA_CH_A_PQM_CH_DESC_PTR_RLS_MSG_PAYLOAD */
#define PDMA_CH_A_PQM_CH_DESC_PTR_RLS_MSG_PAYLOAD_VAL_S 0
#define PDMA_CH_A_PQM_CH_DESC_PTR_RLS_MSG_PAYLOAD_VAL_M 0xFFFFFFFF

/* PDMA_CH_A_PQM_CH_FENCE_INC */
#define PDMA_CH_A_PQM_CH_FENCE_INC_VAL_S 0
#define PDMA_CH_A_PQM_CH_FENCE_INC_VAL_M 0xF

/* PDMA_CH_A_PQM_CH_FENCE_CNT */
#define PDMA_CH_A_PQM_CH_FENCE_CNT_VAL_S 0
#define PDMA_CH_A_PQM_CH_FENCE_CNT_VAL_M 0x3FFF

/* PDMA_CH_A_PQM_CH_MSQ_BASE_H */
#define PDMA_CH_A_PQM_CH_MSQ_BASE_H_VAL_S 0
#define PDMA_CH_A_PQM_CH_MSQ_BASE_H_VAL_M 0xFFFFFFFF

/* PDMA_CH_A_PQM_CH_MSQ_BASE_L */
#define PDMA_CH_A_PQM_CH_MSQ_BASE_L_VAL_S 0
#define PDMA_CH_A_PQM_CH_MSQ_BASE_L_VAL_M 0xFFFFFFFF

/* PDMA_CH_A_PQM_CH_MSQ_SIZE */
#define PDMA_CH_A_PQM_CH_MSQ_SIZE_VAL_S 0
#define PDMA_CH_A_PQM_CH_MSQ_SIZE_VAL_M 0x3FFFFFFF

/* PDMA_CH_A_PQM_CH_MSQ_PI */
#define PDMA_CH_A_PQM_CH_MSQ_PI_VAL_S 0
#define PDMA_CH_A_PQM_CH_MSQ_PI_VAL_M 0xFFFFFFFF

/* PDMA_CH_A_PQM_CH_MSQ_CI */
#define PDMA_CH_A_PQM_CH_MSQ_CI_VAL_S 0
#define PDMA_CH_A_PQM_CH_MSQ_CI_VAL_M 0xFFFFFFFF

/* PDMA_CH_A_PQM_CH_DESC_SUBMIT_PUSH_REG2 */
#define PDMA_CH_A_PQM_CH_DESC_SUBMIT_PUSH_REG2_PTR_SIZE_S 0
#define PDMA_CH_A_PQM_CH_DESC_SUBMIT_PUSH_REG2_PTR_SIZE_M 0xFFFF
#define PDMA_CH_A_PQM_CH_DESC_SUBMIT_PUSH_REG2_INDEX_S 16
#define PDMA_CH_A_PQM_CH_DESC_SUBMIT_PUSH_REG2_INDEX_M 0x3FF0000

/* PDMA_CH_A_PQM_CH_DESC_SUBMIT_PUSH_REG1 */
#define PDMA_CH_A_PQM_CH_DESC_SUBMIT_PUSH_REG1_VAL_S 0
#define PDMA_CH_A_PQM_CH_DESC_SUBMIT_PUSH_REG1_VAL_M 0xFFFFFFFF

/* PDMA_CH_A_PQM_CH_DESC_SUBMIT_PUSH_REG0 */
#define PDMA_CH_A_PQM_CH_DESC_SUBMIT_PUSH_REG0_VAL_S 0
#define PDMA_CH_A_PQM_CH_DESC_SUBMIT_PUSH_REG0_VAL_M 0xFFFFFFFF

/* PDMA_CH_A_PQM_CH_CQ_RECONFIG */
#define PDMA_CH_A_PQM_CH_CQ_RECONFIG_EN_S 0
#define PDMA_CH_A_PQM_CH_CQ_RECONFIG_EN_M 0x1

#endif /* ASIC_REG_PDMA_CH_A_PQM_CH_MASKS_H_ */
